local composter = exile_composter

local function is_compostable_name(item_name)
    local def = minetest.registered_items[item_name]
    if not def then
        return false
    end

    local groups = def.groups or {}
    local is_plant = (groups.flora or 0) > 0
        or (groups.fibrous_plant or 0) > 0
        or (groups.woody_plant or 0) > 0
        or (groups.cane_plant or 0) > 0
        or (groups.mushroom or 0) > 0
    local is_animal = item_name:sub(1, 8) == "animals:"
    local is_edible = (groups.edible or 0) > 0
    local has_compost_group = (groups.compost or 0) > 0

    return is_plant or is_animal or is_edible or has_compost_group
end

composter.is_compostable_name = is_compostable_name

function composter.get_composter_formspec(compost)
    local formspec = "size[8,4.8]"
        .. "label[0,0;Composter: "
        .. compost
        .. "%]"
        .. "list[current_name;main;0,0.5;2,2]"
        .. "list[current_name;output;4,0.5;4,2]"
        .. "list[current_player;main;0,3;8,4;]"
        .. "listring[current_name;main]"
        .. "listring[current_name;output]"
        .. "listring[current_player;main]"
        .. "image[2.5,1;1,1;exile_composter_arrow.png;]"
    return formspec
end

-- seconds before the next composting validation
composter.seconds_to_compost = 60

-- items that can be generated by composting
composter.generate_items = {
    {
        name = "exile_composter:humus",
        chance = 25,
        cost = 3,
    },
    {
        name = "exile_composter:vermicompost",
        chance = 8,
        cost = 2,
    },
    {
        name = "animals:carcass_invert_small",
        chance = 1,
        cost = 8,
    },
}

function composter.generate_compost(inv, compost)
    -- Check the chances of generating items
    for _, item in ipairs(composter.generate_items) do
        if compost >= item.cost and math.random(1, 100) <= item.chance then
            if inv:room_for_item("output", item.name) then
                -- add the item to the output inventory
                inv:add_item("output", item.name)
                -- decrease compost level
                compost = compost - item.cost
            end
        end
    end
    return compost
end

function composter.process_compostable_items(inv, compost)
    -- Compost value is based on quantity: each consumed item adds 1 compost.
    for _, item in ipairs(inv:get_list("main")) do
        if item and item:get_count() > 0 then
            local name = item:get_name()
            if is_compostable_name(name) then
                if compost < 100 then
                    inv:remove_item("main", ItemStack(name .. " 1"))
                    compost = compost + 1
                end
            end
        end
    end
    return compost
end
